export type Niveau = 'P2' | 'D1';
export type Sem = 'S1' | 'S2';

export const CURRICULUM: Record<Niveau, Record<Sem, string[]>> = {
  P2: {
    S1: ['Cardiologie', 'Pneumologie', 'Nutrition', 'Pharmacologie', 'Hémato'],
    S2: ['Appareil Locomoteur', 'Dermatologie', 'Tête et cou', 'Immunologie', 'Biopathologie'],
  },
  D1: {
    S1: ['Appareil digestif', 'Génétique / Pédiatrie', 'SSH', 'Hormonologie', 'Neurosensoriel'],
    S2: ['Néphrologie', 'AEM', 'Sémiologie écrite', 'Infectiologie', 'Psychiatrie'],
  },
};

// Cours prédéfinis par matière
export const COURSES: Record<string, string[]> = {

  // ── P2 ───────────────────────────────────────────────────────────────────

  'Appareil Locomoteur': [
    'Anatomie du membre sup',
    'Physiopathologie tissulaire et moléculaire',
    'Sémiologie rhumatologie',
    'Physiologie musculaire',
    'Anatomie du membre inférieur (1)',
    'Équilibre et posture',
    'Anatomie du membre inférieur (2)',
    'Anatomie du rachis (1)',
    'Somesthésie douleur',
    'Séméiologie chirurgicale - hanche',
    'Sémiologie chirurgicale - épaule',
    'Sémiologie chirurgicale - genou',
    'Sémiologie chirurgicale - rachis',
    'Rachialgie et radiculalgie',
    'Anatomie du rachis (2)',
    'Séméiologie chirurgicale - membre supérieur',
    'Anatomie du rachis (3)',
    'Histo et histopatho du tissu musculaire strié squelettique',
    'Radioanatomie ostéoarticulaire',
    'Médecine physique et de réadaptation',
    'Sémiologie de l\'image en médecine nucléaire',
    'Séméiologie rhumatologie - arthrite',
    'Séméiologie rhumatologie - os',
  ],

  'Dermatologie': [
    'ED) Synthèse et Mise en situation',
    'Sémio Chir tumeurs cutanés/cicatrisation',
    'Sémio Macules modifiant couleur + Lésions contenu liquidien',
    'Sémio peau enfant puis Sémio des phanères et muqueuses',
    'Physio Pigmentation et Pharmacologie',
    'Examens complémentaires (S)',
    'Examens complémentaires (A)',
    'Anapath 1',
    'ED Debriefing histo',
    'Semio examen clinique introduction',
    'E-learning HISTO',
    'Sémio lésions squameuses/kératosiques + Lésions modifiant consistance peau',
    'Sémio: Lésions modifiant le relief de la peau + perte substance',
    'Chirurgie tumeurs cutanées / cicatrisation',
    'Anapath 2',
  ],

  'Tête et cou': [
    'Histologie organe des sens',
    'Biophysique et physiologie de l\'audition',
    'Neurophysiologie de la vision',
    'Sémiologie maxillo',
    'Sémiologie otologique',
    'Sémiologie pharyngol laryngée et cervicale',
    'Sémiologie rhinologique',
    'Sémiologie ophtalmique',
  ],

  // ── D1 S1 ─────────────────────────────────────────────────────────────────

  'Neurosensoriel': [
    'Histologie du système nerveux (1)',
    'Neuro-anat (1)',
    'Neuro-anat (2)',
    'Neuro-anat (3)',
    'Neuro-anat (4)',
    'Neuro-anat (5)',
    'Neuro-anat (6)',
    'Histologie du système nerveux (2)',
    'Motricité (1)',
    'Motricité (2)',
    'Comportements fondamentaux',
    'Mémoire',
    'Douleur',
    'Fonctions exécutives',
    'Olfaction-gustation',
    'Physiologie du sommeil',
    'Neuropharmacologie',
    'Anatomie radiologique (1)',
    'Anatomie radiologique (2)',
    'Sémio neurologique périphérique',
    'Sémio des nerfs crâniens',
    'Sémio radiculaire',
    'Sémiologie confusions (2024-2025)',
    'Sémio des comas',
    'Sémio hémisphérique',
    'Sémio des aphasies',
    'Sémio épileptique',
    'Sémio des troubles somatoformes',
    'Sémio des troubles psychotropes',
    'Sémiologie des troubles anxieux',
    'Développement normal et pathologique de l\'enfant',
    'Troubles de l\'humeur',
    'Sémio des syndromes cérébelleux',
  ],

  'Appareil digestif': [
    'Anatomie de la paroi abdominale',
    'Anatomie duodénum et pancréas',
    'Anatomie de l\'oesophage et de l\'aorte',
    'Péritoine estomac',
    'Anatomie du foie et des voies biliaires',
    'Sémiologie chirurgicale 2024-2025',
    'Histologie (1-1)',
    'Anatomie rate grêle',
    'Histologie cavité buccale et glandes salivaires (1-2, 1-3)',
    'Histologie de l\'appareil digestif supérieur (2)',
    'Histologie du gros intestin, de l\'appendice, du pancréas, du foie et des voies biliaires (3)',
    'Physiologie de la motricité digestive',
    'Physiologie foie/pancréas',
    'Anapathologie 1 digestif',
    'Anatomopathologie foie et pancréas',
    'Anatomie colon rectum',
    'Semiologie oesogastrique',
    'Sémiologie du tube digestif',
    'Semiologie du foie',
    'Semiologie radiologique 1',
    'Semiologie radiologique 2',
    'Pharmacologie pathologies',
    'Sémiologie voies biliaires et pancréas',
    'Sémiologies chirurgicale',
  ],

  'Génétique / Pédiatrie': [
    'Introduction génétique',
    'Hérédité non mendélienne',
    'Hérédité multifactorielle',
    'Architecture, structure et fonction du génome humain',
    'Mutations dynamiques de l\'ADN et syndrome de l\'X-fragile',
    'Cytogénétique conventionnelle : anomalies des autosomes (trisomie 21) et des gonosomes',
    'Cytologie moléculaire',
    'Techniques d\'analyse des anomalies génétiques à l\'échelle du gène',
    'Interprétation des variants ponctuels',
    'Génétique des populations',
    'Génétique prédictive',
    'Diagnostic prénatal et diagnostic pré implantatoire',
    'Dépistage prénatal',
    'Mucoviscidose',
    'Perspectives thérapeutiques',
    'Oncogénétique',
    'Examen clinique en pédiatrie',
    'Développement psychomoteur de l\'enfant',
    'Séméiologie du nouveau-né',
    'Séméiologie pédiatrique',
  ],

  'SSH': [
    'Principes de l\'épidémiologie descriptive',
    'Principes de l\'épidémiologie descriptive (suite)',
    'Systèmes et politiques de santé en France',
    'Démarches en santé publique',
    'Evaluation du fardeau des maladies',
    'Vaccinations',
    'Dépistage des cancers',
    'Dépistage néonatal',
    'Radioprotection',
    'Ethique générale',
    'Approche transversale du corps',
    'Ethique médicale',
    'Ethique générale (suite) – Ethique de la fin de vie',
    'Apport des registres de maladie',
  ],

  'Hormonologie': [
    'Généralités-Hormonologie',
    'Dosages hormonaux',
    'Principes généraux d\'endocrinologie',
    'Biosynthèse des hormones surrénaliennes',
    'Physiologie de l\'axe hypothalamo-hypophysaire',
    'Physiologie de la régulation de la pression artérielle',
    'Physiologie parathyroïdienne et métabolisme phosphocalcique',
    'Histologie du complexe hypothalamo-hypophysaire',
    'Les glandes surrénales',
    'Médicaments gonadotropes',
    'Tumeurs hypophysaire, acromégalie, hyperprolactinémie',
    'Physiologie corticosurrénale, insuffisance surrénalienne, cushing',
    'Imagerie non isotopique',
    'Histologie de la thyroïde et parathyroïde',
    'Histologie du pancréas',
    'Imagerie isotopique',
    'Parathyroïdes',
    'Physiologie thyroïdienne, goitres et nodules',
    'Diabète insipide / HTA endocrine',
    'Dysthyroïdies',
    'Hypogonadisme + hirsutisme',
    'Retard/avance pubertaire et retard de croissance',
    'Homéostasie glucidique',
    'Diabète sucré',
    'Diagnostic de grossesse - sémiologie GS normale',
    'Axe gonadotrope + régulation fonctions ovariennes',
    'Antidiabétiques',
    'Corticothérapie',
    'Médicaments hypolipémiants',
    'Médicaments de l\'obésité',
    'Sémiologie gynécologique',
    'Fonctions testiculaires',
    'Hypoglycémies : physiopathologie et sémiologie',
    'Biomarqueurs du diabète',
    'Insuffisance surrénalienne',
  ],

  // ── D1 S2 ─────────────────────────────────────────────────────────────────

  'Néphrologie': [
    'Physiologie : compartiments liquidiens-EL',
    'Anatomie des reins, des glandes surrénales et des pédicules rénaux',
    'Anatomie des uretères, de la vessie et anatomie fonctionnelle de la miction',
    'Equilibre acide-base-EL',
    'Physiologie rénale 1-EL',
    'Physiologie rénale (partie 2)',
    'Sémiologie radio',
    'Sémiologie : imagerie fonctionnelle',
    'Anapath 1 : embryologie et histologie de l\'appareil urinaire',
    'Anapath 1 : histologie des voies urinaires excrétrices et de la prostate',
    'Anapath 2 : introduction à la néphropathologie-EL',
    'Anapath 3 : uropathologie',
    'Sémiologie urologique adulte-EL',
    'Sémiologie urologique pédiatrique',
    'Sémiologie néphrologique adulte-EL',
    'Sémiologie néphro pédiatrique',
    'Physiopathologie des néphropathies glomérulaires-EL',
    'Physiopathologie des troubles de l\'hydratation-EL',
    'Adaptation des fonctions rénales à la réduction néphronique',
    'Pharmacologie : médicaments du système rénine angiotensine aldostérone-EL',
    'Pharmacologie : les diurétiques-EL',
    'Reins et médicaments',
    'Les immunosuppresseurs',
  ],

  'AEM': [
    'Item 1',
    'Item 9',
    'Item 1/2/3',
    'Item 17/18',
    'Item 5/6/16/19',
    'Item 8',
    'Item 7',
    'Item 11',
    'Item 13/14',
    'Item 181/182',
    'Item 183/184',
    'Item 365',
    'Item 325',
    'Item 327',
  ],

  'Infectiologie': [
    'Agent infectieux',
    'Épidémiologie des maladies transmissibles',
    'Principaux moyens d\'étude : mise en évidence des agents infectieux',
    'Morphologie et structure bactériennes',
    'Physiologie bactérienne, pouvoir pathogène des bactéries',
    'Génétique bactérienne',
    'Flores commensales et microbiote',
    'Staphylocoques, streptocoques, pneumocoques',
    'Entérobactéries et Campylobacter, Helicobacter',
    'Mycobacterium tuberculosis',
    'Bactéries responsables d\'infections respiratoires : Haemophilus, Bordetella, Legionella, bactéries multi-résistantes et infections liées aux soins',
    'Bactéries responsables d\'infections sexuellement transmissibles : Chlamydia trachomatis, Neisseria gonorrhoeae, Mycoplasma genitalium, Syphilis',
    'Neisseria meningitidis, Listeria monocytogenes',
    'Les antibiotiques, structure, mode d\'action, mécanismes de résistance (ronéo 2024-2025)',
    'Les antibiotiques, structure, mode d\'action, mécanismes de résistance (support moodle)',
    'Parasitologie : introduction',
    'Protozooses : la toxoplasmose',
    'Protozooses : le paludisme',
    'Parasitoses autochtones fréquentes (Giardiose – Oxyurose – Taeniasis – Toxocarose)',
    'Parasitoses tropicales début (Ascaridiose - Anguillulose - Bilharziose)',
    'Parasitoses tropicales suite (Amibiase – Leishmanioses cutanée, cutanéomuqueuse et viscérale)',
    'Cryptosporidioses – Microsporidioses intestinales',
    'Entomologie médicale : scabiose, pédiculose',
    'Introduction à la mycologie médicale',
    'Levuroses (candidoses, cryptococcose, malassezioses) partie 1',
    'Levuroses (candidoses, cryptococcoses, malassezioses) partie 2',
    'Dermatophytoses',
    'Aspergilloses',
    'Pneumocystose',
    'Structure et réplication des virus',
    'Traitements anti-viraux',
    'Viroses à transmission oro-fécales',
    'Méningo-encéphalites virales',
    'Papillomavirus humains',
    'Infections rétrovirales : VIH et HTLV',
    'Grippe et autres viroses respiratoires',
    'Infections virales du voyageur et viroses émergentes',
    'Herpesviridae',
    'Virus et grossesse',
    'Exanthèmes viraux',
    'Hépatites virales',
    'Devenir des maladies infectieuses : hygiène, éducation, environnements nosocomiaux, systèmes de surveillance',
    'Devenir des maladies infectieuses : la vaccination 2024-2025',
    'Devenir des maladies infectieuses : vaccinations',
  ],

  'Psychiatrie': [
    'KFP 1',
    'DP 1',
    'DP 2',
    'KFP 2',
  ],
};

export const ANNEES = [2025, 2024, 2023, 2022, 2021, 2020, 2019, 2018];

export function getAllMatieres(niveau: Niveau): string[] {
  return [...CURRICULUM[niveau].S1, ...CURRICULUM[niveau].S2];
}
